"""empty message

Revision ID: ea2c134b1228
Revises: c60754f89840
Create Date: 2018-05-03 13:36:20.057190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea2c134b1228'
down_revision = 'c60754f89840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('info_reponame_key', 'info', type_='unique')
    op.drop_constraint('info_username_key', 'info', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('info_username_key', 'info', ['username'])
    op.create_unique_constraint('info_reponame_key', 'info', ['reponame'])
    # ### end Alembic commands ###
